### ISSUE TITLE
How to run generators for components, containers, etc?

### ISSUE THREAD

**Issue by jazzido** [iiegor/generator-react-webpack-node#1]
I've just generated an app skeleton, but can't figure out how to execute the generators for components, containers and reducers.

Thanks!

**Comment by iiegor** [comment]
Hello, @jazzido!

Here are all the commands you can run at the moment:
`yo react-webpack-node` _Generate the project structure_
`yo react-webpack-node:component myComponent` _Create a component (with stylesheet)_
`yo react-webpack-node:reducer myReducer` _Create a reducer_
`yo react-webpack-node:container myContainer` _Create a container_
`yo react-webpack-node:constant index MY_CONST` _Create a constant (where index is the constants file name)_

I updated the [README.md](https://github.com/iiegor/generator-react-webpack-node/blob/master/README.md) with some information about this, thanks!

**Comment by jazzido** [comment]
Thanks for your reply, @iiegor.
I'm getting an error message:

```
$ yo react-webpack-node:component myComponent
Error react-webpack-node:component myComponent

You don't seem to have a generator with the name react-webpack-node:component installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 1 registered generators run yo with the `--help` option.
```

**Comment by iiegor** [comment]
@jazzido Try with the new release 0.1.1 :+1:

**Comment by jazzido** [comment]
Works OK now, thanks!
